# Setup

In [1]:
import sys
import os

import re
import collections
import itertools
import bcolz
import pickle
sys.path.append('../../lib')

import numpy as np
import pandas as pd
import gc
import random
import smart_open
import h5py
import csv
import json
import functools
import time
import string

import datetime as dt
from tqdm import tqdm_notebook as tqdm

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

random_state_number = 967898

In [2]:
import tensorflow as tf
from tensorflow.python.client import device_lib
def get_available_gpus():
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos if x.device_type == 'GPU']

config = tf.ConfigProto()
config.gpu_options.allow_growth=True
sess = tf.Session(config=config)
get_available_gpus()

['/gpu:0', '/gpu:1']

In [3]:
%pylab
%matplotlib inline
%load_ext line_profiler
%load_ext memory_profiler
%load_ext autoreload

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/IPython/core/magics/pylab.py:160: UserWarning: pylab import has clobbered these variables: ['random']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [4]:
pd.options.mode.chained_assignment = None
pd.options.display.max_columns = 999
color = sns.color_palette()

# Data

In [5]:
store = pd.HDFStore('../data_prep/processed/stage1/data_frames.h5')
train_df = store['train_df']
test_df = store['test_df']

In [6]:
display(train_df.head())
display(test_df.head())

ID      Gene                Variation  Class  \
0   0  [fam58a]  [truncating, mutations]      1   
1   1     [cbl]                  [w802*]      2   
2   2     [cbl]                  [q249e]      2   
3   3     [cbl]                  [n454d]      3   
4   4     [cbl]                  [l399v]      4   

                                           Sentences  
0  [[cyclin-dependent, kinases, , cdks, , regulat...  
1  [[abstract, background, non-small, cell, lung,...  
2  [[abstract, background, non-small, cell, lung,...  
3  [[recent, evidence, has, demonstrated, that, a...  
4  [[oncogenic, mutations, in, the, monomeric, ca...

ID       Gene Variation                                          Sentences
0   0    [acsl4]   [r570s]  [[2, this, mutation, resulted, in, a, myelopro...
1   1    [naglu]   [p521l]  [[abstract, the, large, tumor, suppressor, 1, ...
2   2      [pah]   [l333f]  [[vascular, endothelial, growth, factor, recep...
3   3     [ing1]   [a148d]  [[inflammatory, myofibroblastic, tumor, , imt,...
4   4  [tmem216]    [g77a]  [[abstract, retinoblastoma, is, a, pediatric, ...

In [7]:
with open('../data_prep/processed/stage1/vocab_words_wordidx.pkl', 'rb') as f:
    (vocab_words, vocab_wordidx) = pickle.load(f)
vocab_size = len(vocab_words)
vocab_size, len(vocab_wordidx)

(352220, 352220)

## Train-Test Split and Data Prep

In [8]:
from sklearn.model_selection import train_test_split, StratifiedShuffleSplit
from sklearn.metrics import make_scorer, f1_score, precision_score, accuracy_score, log_loss
f1_scorer = make_scorer(f1_score, average="macro")
precision_scorer = make_scorer(precision_score, average="macro")
accuracy_scorer = make_scorer(accuracy_score, average="macro")
log_loss_scorer = make_scorer(log_loss)

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score, GridSearchCV, RandomizedSearchCV

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

In [9]:
train_df.Sentences = train_df.Sentences.apply(lambda ll: list(itertools.chain.from_iterable(ll)))
all_text_train_df = pd.DataFrame()
all_text_train_df["Text"] = train_df.Gene + train_df.Variation + train_df.Sentences
all_text_train_df["Class"] = train_df.Class
display(all_text_train_df.head())

Text  Class
0  [fam58a, truncating, mutations, cyclin-depende...      1
1  [cbl, w802*, abstract, background, non-small, ...      2
2  [cbl, q249e, abstract, background, non-small, ...      2
3  [cbl, n454d, recent, evidence, has, demonstrat...      3
4  [cbl, l399v, oncogenic, mutations, in, the, mo...      4

In [10]:
x_train, x_test, y_train, y_test = train_test_split(all_text_train_df.Text,all_text_train_df.Class,
                                                   test_size=0.10, random_state=random_state_number,
                                                   stratify=all_text_train_df.Class)

print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(2988,) (2988,)
(333,) (333,)


In [11]:
del all_text_train_df
del train_df
#del test_df

In [12]:
cvec = CountVectorizer(vocabulary=vocab_wordidx)
tfidf = TfidfTransformer()

In [13]:
x_train = x_train.str.join(" ")
x_train_counts = cvec.fit_transform(x_train, y_train)
print(x_train_counts.shape)
x_train_tf = tfidf.fit_transform(x_train_counts)
print(x_train_tf.shape)

(2988, 352220)
(2988, 352220)


In [14]:
x_test = x_test.str.join(" ")
x_test_counts = cvec.fit_transform(x_test, y_test)
print(x_test_counts.shape)
x_test_tf = tfidf.fit_transform(x_test_counts)
print(x_test_tf.shape)

(333, 352220)
(333, 352220)


In [15]:
len(x_test)

333

In [16]:
gc.collect()

197

In [17]:
def evaluate_model(model, sparse=True, predict_proba=True):
    if sparse:
        x_train_loc = x_train_tf
        y_train_loc = y_train
        x_test_loc  = x_test_tf
        y_test_loc  = y_test
    else:
        x_train_loc = x_train_tf.toarray()
        y_train_loc = y_train.values
        x_test_loc  = x_test_tf.toarray()
        y_test_loc  = y_test.values
        
    model.fit(x_train_loc, y_train_loc)        
    if predict_proba and 'predict_proba' in dir(model):
        predicted_prob = model.predict_proba(x_test_loc)
        print("log_loss\n", log_loss(y_test_loc, predicted_prob, labels=range(1,10)))
        
    y_pred = model.predict(x_test_loc)
    print("f1_score\n", f1_score(y_test_loc, y_pred, average="macro"))
    print("accuracy_score\n", accuracy_score(y_test_loc, y_pred))
    print("\nclassification_report\n",classification_report(y_test_loc, y_pred))
    print("\nconfusion_matrix\n",confusion_matrix(y_test_loc, y_pred))

# Models

did not run GaussianProcessClassifier, GaussianMixture since they took more than 64G of ram

## Multinomial NB

In [19]:
from sklearn.naive_bayes import MultinomialNB
nb_model = MultinomialNB(alpha=0.001)

In [20]:
evaluate_model(nb_model)

log_loss
 1.7626723557
f1_score
 0.581177607313
accuracy_score
 0.663663663664

classification_report
              precision    recall  f1-score   support

          1       0.61      0.58      0.59        57
          2       0.64      0.64      0.64        45
          3       0.45      0.56      0.50         9
          4       0.63      0.59      0.61        69
          5       0.50      0.62      0.56        24
          6       0.84      0.57      0.68        28
          7       0.75      0.83      0.79        95
          8       0.00      0.00      0.00         2
          9       1.00      0.75      0.86         4

avg / total       0.67      0.66      0.66       333


confusion_matrix
 [[33  0  2 17  4  0  1  0  0]
 [ 0 29  0  1  1  0 14  0  0]
 [ 0  0  5  1  1  0  2  0  0]
 [16  0  1 41  6  2  3  0  0]
 [ 1  1  0  3 15  1  3  0  0]
 [ 3  4  0  1  2 16  2  0  0]
 [ 1 10  3  1  1  0 79  0  0]
 [ 0  1  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  1  0  3]]


/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [24]:
parameters = { 'alpha': [0.0005, 0.001,0.002,0.01,0.02]  }

nb_gs = GridSearchCV(nb_model, parameters)

In [25]:
evaluate_model(nb_gs)

log_loss
 1.7626723557
f1_score
 0.581177607313
accuracy_score
 0.663663663664

classification_report
              precision    recall  f1-score   support

          1       0.61      0.58      0.59        57
          2       0.64      0.64      0.64        45
          3       0.45      0.56      0.50         9
          4       0.63      0.59      0.61        69
          5       0.50      0.62      0.56        24
          6       0.84      0.57      0.68        28
          7       0.75      0.83      0.79        95
          8       0.00      0.00      0.00         2
          9       1.00      0.75      0.86         4

avg / total       0.67      0.66      0.66       333


confusion_matrix
 [[33  0  2 17  4  0  1  0  0]
 [ 0 29  0  1  1  0 14  0  0]
 [ 0  0  5  1  1  0  2  0  0]
 [16  0  1 41  6  2  3  0  0]
 [ 1  1  0  3 15  1  3  0  0]
 [ 3  4  0  1  2 16  2  0  0]
 [ 1 10  3  1  1  0 79  0  0]
 [ 0  1  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  1  0  3]]


/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [26]:
pd.DataFrame(nb_gs.cv_results_).transpose()

/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
 

0                 1                 2  \
mean_fit_time                 0.28587           0.23958          0.243783   
mean_score_time             0.0435839          0.039856         0.0404784   
mean_test_score              0.610776          0.614123          0.614123   
mean_train_score             0.831156          0.828478          0.817602   
param_alpha                    0.0005             0.001             0.002   
params              {'alpha': 0.0005}  {'alpha': 0.001}  {'alpha': 0.002}   
rank_test_score                     3                 1                 1   
split0_test_score              0.5996          0.612613          0.602603   
split0_train_score           0.824032          0.822524          0.812469   
split1_test_score            0.601805          0.603811          0.610832   
split1_train_score           0.838774          0.834254            0.8222   
split2_test_score            0.631048          0.626008          0.629032   
split2_train_score           0.830661          0.828657          0.818136   
std_fit_time                 0.026271        0.00430358        0.00414162   
std_score_time              0.0026256        0.00115544       0.000774844   
std_test_score              0.0143197        0.00911794         0.0110356   
std_train_score            0.00602868        0.00479053        0.00399075   

                                  3                4  
mean_fit_time              0.239334         0.241517  
mean_score_time           0.0392499        0.0399577  
mean_test_score            0.602075         0.577309  
mean_train_score           0.740794         0.699124  
param_alpha                    0.01             0.02  
params              {'alpha': 0.01}  {'alpha': 0.02}  
rank_test_score                   4                5  
split0_test_score          0.597598         0.577578  
split0_train_score         0.735043         0.689794  
split1_test_score          0.600802         0.579739  
split1_train_score         0.745354         0.705676  
split2_test_score          0.607863         0.574597  
split2_train_score         0.741984         0.701904  
std_fit_time             0.00114185       0.00356728  
std_score_time          0.000714229      0.000626832  
std_test_score            0.0042854       0.00210641  
std_train_score          0.00429292       0.00677499

## Support Vector Machine

In [27]:
from sklearn.svm import SVC
svc_model = SVC(probability=True)

In [28]:
evaluate_model(svc_model)

log_loss
 1.8784669174
f1_score
 0.0493250259605
accuracy_score
 0.285285285285

classification_report
              precision    recall  f1-score   support

          1       0.00      0.00      0.00        57
          2       0.00      0.00      0.00        45
          3       0.00      0.00      0.00         9
          4       0.00      0.00      0.00        69
          5       0.00      0.00      0.00        24
          6       0.00      0.00      0.00        28
          7       0.29      1.00      0.44        95
          8       0.00      0.00      0.00         2
          9       0.00      0.00      0.00         4

avg / total       0.08      0.29      0.13       333


confusion_matrix
 [[ 0  0  0  0  0  0 57  0  0]
 [ 0  0  0  0  0  0 45  0  0]
 [ 0  0  0  0  0  0  9  0  0]
 [ 0  0  0  0  0  0 69  0  0]
 [ 0  0  0  0  0  0 24  0  0]
 [ 0  0  0  0  0  0 28  0  0]
 [ 0  0  0  0  0  0 95  0  0]
 [ 0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  4  0  0]]


/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [29]:
parameters = {'kernel':('linear', 'rbf'), 
              'C':[1,2,3,4,5,6,7,8,9,10], 
              'gamma':[0.01,0.02,0.03,0.04,0.1,0.2],
              'degree':[3,4,5,6]}

svc_rs = RandomizedSearchCV(svc_model, parameters, n_iter=20, n_jobs=10)

In [30]:
evaluate_model(svc_rs)

log_loss
 0.989794887126
f1_score
 0.49552989396
accuracy_score
 0.633633633634

classification_report
              precision    recall  f1-score   support

          1       0.55      0.58      0.56        57
          2       0.73      0.49      0.59        45
          3       0.17      0.11      0.13         9
          4       0.64      0.67      0.65        69
          5       0.36      0.21      0.26        24
          6       0.88      0.50      0.64        28
          7       0.66      0.92      0.77        95
          8       0.00      0.00      0.00         2
          9       1.00      0.75      0.86         4

avg / total       0.63      0.63      0.62       333


confusion_matrix
 [[33  0  2 17  2  1  2  0  0]
 [ 0 22  0  1  1  0 21  0  0]
 [ 0  0  1  1  1  0  6  0  0]
 [15  0  1 46  3  0  4  0  0]
 [ 6  1  0  5  5  0  7  0  0]
 [ 6  3  0  1  1 14  3  0  0]
 [ 0  4  2  1  1  0 87  0  0]
 [ 0  0  0  0  0  1  1  0  0]
 [ 0  0  0  0  0  0  1  0  3]]


/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [31]:
pd.DataFrame(svc_rs.cv_results_).transpose()

/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
 

0   \
mean_fit_time                                                 412.061   
mean_score_time                                               27.1016   
mean_test_score                                              0.579652   
mean_train_score                                             0.658475   
param_C                                                             6   
param_degree                                                        5   
param_gamma                                                      0.04   
param_kernel                                                      rbf   
params              {'kernel': 'rbf', 'gamma': 0.04, 'degree': 5, ...   
rank_test_score                                                    15   
split0_test_score                                            0.556557   
split0_train_score                                            0.65812   
split1_test_score                                            0.594784   
split1_train_score                                           0.668508   
split2_test_score                                            0.587702   
split2_train_score                                           0.648798   
std_fit_time                                                   12.257   
std_score_time                                               0.225135   
std_test_score                                              0.0166209   
std_train_score                                            0.00805078   

                                                                   1   \
mean_fit_time                                                 436.964   
mean_score_time                                               27.3234   
mean_test_score                                              0.626171   
mean_train_score                                             0.828311   
param_C                                                             4   
param_degree                                                        4   
param_gamma                                                      0.03   
param_kernel                                                   linear   
params              {'kernel': 'linear', 'gamma': 0.03, 'degree': ...   
rank_test_score                                                     1   
split0_test_score                                            0.618619   
split0_train_score                                           0.822021   
split1_test_score                                            0.613842   
split1_train_score                                           0.834756   
split2_test_score                                            0.646169   
split2_train_score                                           0.828156   
std_fit_time                                                  4.78268   
std_score_time                                               0.629112   
std_test_score                                              0.0142327   
std_train_score                                            0.00520031   

                                                                   2   \
mean_fit_time                                                 458.363   
mean_score_time                                               27.3088   
mean_test_score                                              0.465529   
mean_train_score                                              0.49181   
param_C                                                             6   
param_degree                                                        4   
param_gamma                                                      0.01   
param_kernel                                                      rbf   
params              {'kernel': 'rbf', 'gamma': 0.01, 'degree': 4, ...   
rank_test_score                                                    19   
split0_test_score                                            0.476476   
split0_train_score                                           0.506787   
split1_test_score                                 

## Softmax Regression

In [32]:
from sklearn.linear_model import LogisticRegression
smreg_model = LogisticRegression(multi_class="multinomial", solver='lbfgs')

In [33]:
evaluate_model(smreg_model)

log_loss
 1.45620897096
f1_score
 0.264439056896
accuracy_score
 0.507507507508

classification_report
              precision    recall  f1-score   support

          1       0.48      0.56      0.52        57
          2       0.00      0.00      0.00        45
          3       0.00      0.00      0.00         9
          4       0.77      0.43      0.56        69
          5       0.50      0.12      0.20        24
          6       0.77      0.36      0.49        28
          7       0.45      0.99      0.62        95
          8       0.00      0.00      0.00         2
          9       0.00      0.00      0.00         4

avg / total       0.47      0.51      0.44       333


confusion_matrix
 [[32  0  0  3  0  0 22  0  0]
 [ 0  0  0  0  0  0 45  0  0]
 [ 0  0  0  2  1  0  6  0  0]
 [19  0  0 30  2  3 15  0  0]
 [10  0  0  2  3  0  9  0  0]
 [ 6  0  0  1  0 10 11  0  0]
 [ 0  0  0  1  0  0 94  0  0]
 [ 0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  4  0  0]]


/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [34]:
parameters ={
#                 'penalty' : ['l1','l2'],
                'tol' : [1e-5, 1e-4, 1e-3],
                'class_weight' : [None, 'balanced'],
                'max_iter' : [100,150,200,250,300],
#                 'solver' : ['newton-cg', 'lbfgs'], 
                'C':[1,2,3,4,5,6,7,8,9,10], 
            }

smreg_rs = RandomizedSearchCV(smreg_model, parameters, n_jobs=10)

In [35]:
evaluate_model(smreg_rs)

log_loss
 1.27620591928
f1_score
 0.529901181
accuracy_score
 0.600600600601

classification_report
              precision    recall  f1-score   support

          1       0.58      0.60      0.59        57
          2       0.65      0.53      0.59        45
          3       0.26      0.67      0.38         9
          4       0.64      0.55      0.59        69
          5       0.48      0.62      0.55        24
          6       0.80      0.57      0.67        28
          7       0.66      0.67      0.67        95
          8       0.00      0.00      0.00         2
          9       0.75      0.75      0.75         4

avg / total       0.63      0.60      0.61       333


confusion_matrix
 [[34  1  2 13  4  0  3  0  0]
 [ 2 24  0  2  0  0 16  1  0]
 [ 0  0  6  1  1  0  1  0  0]
 [15  0  1 38  7  4  2  2  0]
 [ 2  1  1  2 15  0  3  0  0]
 [ 4  1  0  0  2 16  5  0  0]
 [ 2 10 13  3  2  0 64  0  1]
 [ 0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  1  0  3]]


In [36]:
pd.DataFrame(smreg_rs.cv_results_).transpose()

/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
 

0  \
mean_fit_time                                                 27.5595   
mean_score_time                                              0.168866   
mean_test_score                                              0.296854   
mean_train_score                                             0.300342   
param_C                                                            10   
param_class_weight                                               None   
param_max_iter                                                    250   
param_tol                                                       1e-05   
params              {'tol': 1e-05, 'max_iter': 250, 'class_weight'...   
rank_test_score                                                    10   
split0_test_score                                            0.286286   
split0_train_score                                           0.287582   
split1_test_score                                            0.286861   
split1_train_score                                           0.287293   
split2_test_score                                             0.31754   
split2_train_score                                           0.326152   
std_fit_time                                                  12.0184   
std_score_time                                              0.0860778   
std_test_score                                              0.0145852   
std_train_score                                             0.0182508   

                                                                    1  \
mean_fit_time                                                 198.528   
mean_score_time                                               0.25248   
mean_test_score                                              0.445114   
mean_train_score                                             0.479201   
param_C                                                             8   
param_class_weight                                               None   
param_max_iter                                                    150   
param_tol                                                      0.0001   
params              {'tol': 0.0001, 'max_iter': 150, 'class_weight...   
rank_test_score                                                     5   
split0_test_score                                            0.312312   
split0_train_score                                           0.319759   
split1_test_score                                            0.436309   
split1_train_score                                           0.443998   
split2_test_score                                            0.587702   
split2_train_score                                           0.673848   
std_fit_time                                                  158.091   
std_score_time                                               0.046102   
std_test_score                                               0.112571   
std_train_score                                              0.146684   

                                                                    2  \
mean_fit_time                                                 112.677   
mean_score_time                                              0.213176   
mean_test_score                                              0.455154   
mean_train_score                                             0.521915   
param_C                                                            10   
param_class_weight                                           balanced   
param_max_iter                                                    200   
param_tol                                                      0.0001   
params              {'tol': 0.0001, 'max_iter': 200, 'class_weight...   
rank_test_score                                                     3   
split0_test_score                                            0.448448   
split0_train_score                                           0.524384   
split1_test_score                                  

## K Nearest Neighbour

In [37]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=3)

In [38]:
evaluate_model(knn_model)

log_loss
 8.1949303197
f1_score
 0.477345011858
accuracy_score
 0.612612612613

classification_report
              precision    recall  f1-score   support

          1       0.54      0.47      0.50        57
          2       0.54      0.49      0.51        45
          3       0.00      0.00      0.00         9
          4       0.64      0.77      0.70        69
          5       0.36      0.21      0.26        24
          6       0.94      0.61      0.74        28
          7       0.65      0.81      0.72        95
          8       0.00      0.00      0.00         2
          9       1.00      0.75      0.86         4

avg / total       0.60      0.61      0.60       333


confusion_matrix
 [[27  4  1 19  3  0  3  0  0]
 [ 2 22  1  1  1  0 18  0  0]
 [ 0  0  0  1  2  0  6  0  0]
 [11  0  2 53  1  0  2  0  0]
 [ 5  1  0  6  5  0  7  0  0]
 [ 3  2  0  1  2 17  3  0  0]
 [ 2 12  2  2  0  0 77  0  0]
 [ 0  0  0  0  0  1  1  0  0]
 [ 0  0  0  0  0  0  1  0  3]]


/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [39]:
parameters = {'n_neighbors':[3,4,5], 
              'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute'], 
              'leaf_size':[30,35,40,45,50]
             }

knn_rs = RandomizedSearchCV(knn_model, parameters, n_jobs=10, n_iter=30)


In [40]:
evaluate_model(knn_rs)

/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/neighbors/base.py:212: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: "
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/neighbors/base.py:212: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: "
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/neighbors/base.py:212: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: "
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/neighbors/base.py:212: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: "
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/neighbor

/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/neighbors/base.py:212: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: "
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/neighbors/base.py:212: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: "
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/neighbors/base.py:212: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: "
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/neighbors/base.py:212: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: "
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/neighbor

log_loss
 8.1949303197
f1_score
 0.477345011858
accuracy_score
 0.612612612613

classification_report
              precision    recall  f1-score   support

          1       0.54      0.47      0.50        57
          2       0.54      0.49      0.51        45
          3       0.00      0.00      0.00         9
          4       0.64      0.77      0.70        69
          5       0.36      0.21      0.26        24
          6       0.94      0.61      0.74        28
          7       0.65      0.81      0.72        95
          8       0.00      0.00      0.00         2
          9       1.00      0.75      0.86         4

avg / total       0.60      0.61      0.60       333


confusion_matrix
 [[27  4  1 19  3  0  3  0  0]
 [ 2 22  1  1  1  0 18  0  0]
 [ 0  0  0  1  2  0  6  0  0]
 [11  0  2 53  1  0  2  0  0]
 [ 5  1  0  6  5  0  7  0  0]
 [ 3  2  0  1  2 17  3  0  0]
 [ 2 12  2  2  0  0 77  0  0]
 [ 0  0  0  0  0  1  1  0  0]
 [ 0  0  0  0  0  0  1  0  3]]


/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [41]:
pd.DataFrame(knn_rs.cv_results_).transpose()

/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
 

0   \
mean_fit_time                                                0.206978   
mean_score_time                                               5.54123   
mean_test_score                                              0.570616   
mean_train_score                                             0.692778   
param_algorithm                                                 brute   
param_leaf_size                                                    35   
param_n_neighbors                                                   5   
params              {'n_neighbors': 5, 'leaf_size': 35, 'algorithm...   
rank_test_score                                                    22   
split0_test_score                                            0.562563   
split0_train_score                                           0.699346   
split1_test_score                                            0.570712   
split1_train_score                                           0.691612   
split2_test_score                                            0.578629   
split2_train_score                                           0.687375   
std_fit_time                                                0.0068602   
std_score_time                                               0.405477   
std_test_score                                             0.00655778   
std_train_score                                            0.00495641   

                                                                   1   \
mean_fit_time                                                0.195477   
mean_score_time                                               5.96974   
mean_test_score                                              0.583668   
mean_train_score                                             0.757202   
param_algorithm                                                 brute   
param_leaf_size                                                    50   
param_n_neighbors                                                   3   
params              {'n_neighbors': 3, 'leaf_size': 50, 'algorithm...   
rank_test_score                                                     1   
split0_test_score                                            0.565566   
split0_train_score                                           0.756662   
split1_test_score                                            0.589769   
split1_train_score                                           0.765947   
split2_test_score                                            0.595766   
split2_train_score                                           0.748998   
std_fit_time                                                0.0266201   
std_score_time                                               0.312278   
std_test_score                                              0.0130604   
std_train_score                                            0.00692985   

                                                                   2   \
mean_fit_time                                                0.248091   
mean_score_time                                               6.18311   
mean_test_score                                               0.57162   
mean_train_score                                             0.716873   
param_algorithm                                               kd_tree   
param_leaf_size                                                    30   
param_n_neighbors                                                   4   
params              {'n_neighbors': 4, 'leaf_size': 30, 'algorithm...   
rank_test_score                                                    12   
split0_test_score                                            0.567568   
split0_train_score                                           0.720463   
split1_test_score                                            0.569709   
split1_train_score                                           0.718734   
split2_test_score                                            0.577621   
split2_train_score                                

## Passive Aggresive Classifier

In [42]:
from sklearn.linear_model import PassiveAggressiveClassifier
pag_model = PassiveAggressiveClassifier()

In [43]:
evaluate_model(pag_model, predict_proba=False)

/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/linear_model/stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.passive_aggressive.PassiveAggressiveClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


f1_score
 0.480985363462
accuracy_score
 0.630630630631

classification_report
              precision    recall  f1-score   support

          1       0.75      0.37      0.49        57
          2       0.66      0.51      0.57        45
          3       0.00      0.00      0.00         9
          4       0.54      0.81      0.65        69
          5       0.41      0.38      0.39        24
          6       0.92      0.43      0.59        28
          7       0.68      0.91      0.77        95
          8       0.00      0.00      0.00         2
          9       1.00      0.75      0.86         4

avg / total       0.64      0.63      0.61       333


confusion_matrix
 [[21  0  0 28  4  1  3  0  0]
 [ 0 23  0  2  2  0 18  0  0]
 [ 0  0  0  2  1  0  6  0  0]
 [ 6  0  0 56  3  0  4  0  0]
 [ 0  1  0 10  9  0  4  0  0]
 [ 1  6  0  4  2 12  3  0  0]
 [ 0  5  2  1  1  0 86  0  0]
 [ 0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  1  0  3]]


/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [44]:
parameters = {
              'C':[1,2,3,4,5,6,7,8,9,10], 
              'tol' : [1e-5, 1e-4, 1e-3],
              'max_iter' : [800, 1000,1200],
              'loss':['hinge', 'squared_hinge']}

pag_rs = RandomizedSearchCV(pag_model, parameters, n_iter=100, n_jobs=-1)


In [45]:
evaluate_model(pag_rs, predict_proba=False)

f1_score
 0.509996921376
accuracy_score
 0.633633633634

classification_report
              precision    recall  f1-score   support

          1       0.64      0.53      0.58        57
          2       0.69      0.49      0.57        45
          3       0.00      0.00      0.00         9
          4       0.60      0.61      0.60        69
          5       0.47      0.58      0.52        24
          6       0.78      0.64      0.71        28
          7       0.67      0.86      0.76        95
          8       0.00      0.00      0.00         2
          9       1.00      0.75      0.86         4

avg / total       0.63      0.63      0.62       333


confusion_matrix
 [[30  0  2 19  3  1  2  0  0]
 [ 0 22  1  1  1  1 19  0  0]
 [ 0  0  0  1  2  0  6  0  0]
 [14  0  1 42  6  2  4  0  0]
 [ 1  1  0  4 14  1  3  0  0]
 [ 2  2  0  1  2 18  3  0  0]
 [ 0  7  2  2  2  0 82  0  0]
 [ 0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  1  0  3]]


/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [46]:
pd.DataFrame(pag_rs.cv_results_).transpose()

/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
 

0   \
mean_fit_time                                                 4.69141   
mean_score_time                                              0.189719   
mean_test_score                                              0.598728   
mean_train_score                                              0.82076   
param_C                                                             6   
param_loss                                                      hinge   
param_max_iter                                                    800   
param_tol                                                       1e-05   
params              {'tol': 1e-05, 'max_iter': 800, 'loss': 'hinge...   
rank_test_score                                                    45   
split0_test_score                                            0.536537   
split0_train_score                                            0.78733   
split1_test_score                                            0.617854   
split1_train_score                                           0.840281   
split2_test_score                                            0.642137   
split2_train_score                                           0.834669   
std_fit_time                                                 0.389483   
std_score_time                                              0.0214973   
std_test_score                                              0.0451751   
std_train_score                                             0.0237493   

                                                                   1   \
mean_fit_time                                                 5.17403   
mean_score_time                                              0.240132   
mean_test_score                                              0.596386   
mean_train_score                                             0.820092   
param_C                                                             9   
param_loss                                                      hinge   
param_max_iter                                                   1000   
param_tol                                                      0.0001   
params              {'tol': 0.0001, 'max_iter': 1000, 'loss': 'hin...   
rank_test_score                                                    55   
split0_test_score                                            0.536537   
split0_train_score                                            0.78733   
split1_test_score                                            0.617854   
split1_train_score                                           0.840281   
split2_test_score                                            0.635081   
split2_train_score                                           0.832665   
std_fit_time                                                 0.736332   
std_score_time                                              0.0779554   
std_test_score                                              0.0429935   
std_train_score                                             0.0233739   

                                                                   2   \
mean_fit_time                                                 5.81754   
mean_score_time                                              0.208435   
mean_test_score                                              0.600736   
mean_train_score                                             0.820759   
param_C                                                            10   
param_loss                                              squared_hinge   
param_max_iter                                                    800   
param_tol                                                      0.0001   
params              {'tol': 0.0001, 'max_iter': 800, 'loss': 'squa...   
rank_test_score                                                    36   
split0_test_score                                             0.53954   
split0_train_score                                           0.785319   
split1_test_score                                 

## Quadratic Discriminant Analysis

In [40]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
qda_model = QuadraticDiscriminantAnalysis()

In [41]:
evaluate_model(qda_model, sparse=False)

/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:682: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:683: RuntimeWarning: overflow encountered in square
  S2 = (S ** 2) / (len(Xg) - 1)


LinAlgError: SVD did not converge

## Decision Trees Classifier

In [20]:
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier()

In [21]:
evaluate_model(dt_model)

log_loss
 13.8984865974
f1_score
 0.4952080585
accuracy_score
 0.597597597598

classification_report
              precision    recall  f1-score   support

          1       0.66      0.58      0.62        57
          2       0.49      0.38      0.42        45
          3       0.56      0.56      0.56         9
          4       0.63      0.67      0.65        69
          5       0.31      0.21      0.25        24
          6       0.48      0.50      0.49        28
          7       0.66      0.80      0.72        95
          8       0.00      0.00      0.00         2
          9       0.75      0.75      0.75         4

avg / total       0.58      0.60      0.59       333


confusion_matrix
 [[33  1  0 14  3  3  3  0  0]
 [ 3 17  0  2  4  1 17  0  1]
 [ 0  0  5  1  0  1  2  0  0]
 [10  0  1 46  1  3  7  1  0]
 [ 1  1  0  5  5  5  7  0  0]
 [ 1  6  0  2  2 14  3  0  0]
 [ 1  9  3  3  1  2 76  0  0]
 [ 0  1  0  0  0  0  1  0  0]
 [ 1  0  0  0  0  0  0  0  3]]


In [22]:
parameters = {
              'criterion':['gini','entropy'], 
              'splitter':['best','random'], 
              'max_depth':[None, 4, 6, 8, 10], 
              'min_samples_split':[2,4,6,8],
              'min_samples_leaf':[1, 3, 5, 8, 10], 
              'min_weight_fraction_leaf':[0, 0.1, 0.01, 0.5, 0.001], 
              'max_features':['log2','auto'], 
              'max_leaf_nodes':[None, 4, 8, 16, 32],
              'min_impurity_decrease':[0, 1e-3, 1e-4, 1e-5], 
              'class_weight':['balanced',None],
#               'presort':[True, False] 
}
dt_rs = RandomizedSearchCV(dt_model, parameters, n_iter=100, n_jobs=-1)


In [23]:
evaluate_model(dt_rs)

log_loss
 1.96834503006
f1_score
 0.214009018851
accuracy_score
 0.414414414414

classification_report
              precision    recall  f1-score   support

          1       0.00      0.00      0.00        57
          2       0.27      0.07      0.11        45
          3       0.00      0.00      0.00         9
          4       0.42      0.61      0.50        69
          5       0.50      0.29      0.37        24
          6       0.80      0.29      0.42        28
          7       0.39      0.82      0.53        95
          8       0.00      0.00      0.00         2
          9       0.00      0.00      0.00         4

avg / total       0.34      0.41      0.33       333


confusion_matrix
 [[ 0  0  0 26  1  1 29  0  0]
 [ 0  3  0  6  1  0 35  0  0]
 [ 0  0  0  1  1  0  7  0  0]
 [ 0  0  0 42  2  1 24  0  0]
 [ 0  0  0  6  7  0 11  0  0]
 [ 0  1  0  9  2  8  8  0  0]
 [ 0  7  0 10  0  0 78  0  0]
 [ 0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  4  0  0]]


/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [24]:
pd.DataFrame(dt_rs.cv_results_).transpose()

/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
 

0   \
mean_fit_time                                                            0.313733   
mean_score_time                                                         0.0158895   
mean_test_score                                                          0.336345   
mean_train_score                                                         0.346388   
param_class_weight                                                           None   
param_criterion                                                              gini   
param_max_depth                                                              None   
param_max_features                                                           auto   
param_max_leaf_nodes                                                           16   
param_min_impurity_decrease                                                 0.001   
param_min_samples_leaf                                                          5   
param_min_samples_split                                                         6   
param_min_weight_fraction_leaf                                                0.1   
param_splitter                                                               best   
params                          {'splitter': 'best', 'min_weight_fraction_leaf...   
rank_test_score                                                                12   
split0_test_score                                                        0.325325   
split0_train_score                                                       0.344394   
split1_test_score                                                        0.361083   
split1_train_score                                                       0.352587   
split2_test_score                                                        0.322581   
split2_train_score                                                       0.342184   
std_fit_time                                                           0.00872722   
std_score_time                                                        0.000390884   
std_test_score                                                          0.0175413   
std_train_score                                                        0.00447471   

                                                                               1   \
mean_fit_time                                                             0.32039   
mean_score_time                                                          0.015655   
mean_test_score                                                          0.171352   
mean_train_score                                                         0.171214   
param_class_weight                                                       balanced   
param_criterion                                                              gini   
param_max_depth                                                                10   
param_max_features                                                           auto   
param_max_leaf_nodes                                                            4   
param_min_impurity_decrease                                                 0.001   
param_min_samples_leaf                                                          5   
param_min_samples_split                                                         6   
param_min_weight_fraction_leaf                                                0.5   
param_splitter                                                               best   
params                          {'splitter': 'best', 'min_weight_fraction_leaf...   
rank_test_score                                                                66   
split0_test_score                                                        0.171171   
split0_train_score                                                        0.17094   
split1_test_score                                                         0.20662   
split1_train_score                                                       0.206429  

## AdaBoost Classifier

In [25]:
from sklearn.ensemble import AdaBoostClassifier
adab_model = AdaBoostClassifier()

In [26]:
evaluate_model(adab_model)

log_loss
 2.03696523324
f1_score
 0.171401646976
accuracy_score
 0.408408408408

classification_report
              precision    recall  f1-score   support

          1       0.00      0.00      0.00        57
          2       0.00      0.00      0.00        45
          3       0.00      0.00      0.00         9
          4       0.31      0.84      0.45        69
          5       0.00      0.00      0.00        24
          6       0.00      0.00      0.00        28
          7       0.54      0.80      0.65        95
          8       0.00      0.00      0.00         2
          9       0.40      0.50      0.44         4

avg / total       0.22      0.41      0.28       333


confusion_matrix
 [[ 0  0  0 52  0  0  5  0  0]
 [ 0  0  0 20  0  0 25  0  0]
 [ 0  0  0  3  0  0  6  0  0]
 [ 0  0  0 58  0  0  8  0  3]
 [ 0  0  0 16  0  0  8  0  0]
 [ 0  0  0 19  0  0  9  0  0]
 [ 0  0  0 19  0  0 76  0  0]
 [ 0  0  0  0  0  0  2  0  0]
 [ 0  0  0  1  0  0  1  0  2]]


/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [27]:
parameters = {
              # adaboost
              'n_estimators' :[50, 100, 150, 200, 500],
              'learning_rate':[1e-4, 1e-3, 1e-2, 1e-1],
              'algorithm' : ['SAMME', 'SAMME.R'],
}
adab_rs = RandomizedSearchCV(adab_model, parameters, n_iter=25, n_jobs=-1)


In [28]:
evaluate_model(adab_rs)

log_loss
 2.19089383327
f1_score
 0.22149712825
accuracy_score
 0.465465465465

classification_report
              precision    recall  f1-score   support

          1       0.29      0.40      0.34        57
          2       0.00      0.00      0.00        45
          3       0.00      0.00      0.00         9
          4       0.46      0.57      0.51        69
          5       0.00      0.00      0.00        24
          6       1.00      0.32      0.49        28
          7       0.53      0.88      0.66        95
          8       0.00      0.00      0.00         2
          9       0.00      0.00      0.00         4

avg / total       0.38      0.47      0.39       333


confusion_matrix
 [[23  0  0 31  0  0  3  0  0]
 [12  0  0  0  0  0 33  0  0]
 [ 1  0  0  2  0  0  6  0  0]
 [18  0  0 39  0  0 12  0  0]
 [13  0  0  4  0  0  7  0  0]
 [ 6  0  0  2  0  9 11  0  0]
 [ 6  1  0  4  0  0 84  0  0]
 [ 0  0  0  0  0  0  2  0  0]
 [ 1  0  0  2  0  0  1  0  0]]


/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [29]:
pd.DataFrame(adab_rs.cv_results_).transpose()

/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
 

0   \
mean_fit_time                                                  156.573   
mean_score_time                                                3.49791   
mean_test_score                                               0.389558   
mean_train_score                                              0.392233   
param_algorithm                                                  SAMME   
param_learning_rate                                              0.001   
param_n_estimators                                                 200   
params               {'n_estimators': 200, 'learning_rate': 0.001, ...   
rank_test_score                                                     14   
split0_test_score                                             0.368368   
split0_train_score                                            0.385621   
split1_test_score                                             0.412237   
split1_train_score                                            0.398292   
split2_test_score                                             0.388105   
split2_train_score                                            0.392786   
std_fit_time                                                   7.26163   
std_score_time                                                0.800182   
std_test_score                                               0.0179564   
std_train_score                                             0.00518782   

                                                                    1   \
mean_fit_time                                                  38.2216   
mean_score_time                                               0.770263   
mean_test_score                                                0.39257   
mean_train_score                                              0.396753   
param_algorithm                                                  SAMME   
param_learning_rate                                               0.01   
param_n_estimators                                                  50   
params               {'n_estimators': 50, 'learning_rate': 0.01, 'a...   
rank_test_score                                                     13   
split0_test_score                                             0.361361   
split0_train_score                                            0.394671   
split1_test_score                                              0.41324   
split1_train_score                                            0.398795   
split2_test_score                                             0.403226   
split2_train_score                                            0.396794   
std_fit_time                                                    0.3919   
std_score_time                                               0.0159834   
std_test_score                                                0.022492   
std_train_score                                             0.00168381   

                                                                    2   \
mean_fit_time                                                  381.323   
mean_score_time                                                 7.3015   
mean_test_score                                                0.44344   
mean_train_score                                               0.48713   
param_algorithm                                                SAMME.R   
param_learning_rate                                                0.1   
param_n_estimators                                                 500   
params               {'n_estimators': 500, 'learning_rate': 0.1, 'a...   
rank_test_score                                                      4   
split0_test_score                                             0.426426   
split0_train_score                                            0.494721   
split1_test_score                                             0.472417   
split1_train_score                                            0.494726   
split2_test_score                                             0.431452

## Random Forest Classifier

In [30]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier()

In [31]:
evaluate_model(rf_model)

log_loss
 3.71404558515
f1_score
 0.551773156393
accuracy_score
 0.627627627628

classification_report
              precision    recall  f1-score   support

          1       0.51      0.51      0.51        57
          2       0.59      0.38      0.46        45
          3       0.83      0.56      0.67         9
          4       0.67      0.67      0.67        69
          5       0.55      0.25      0.34        24
          6       0.79      0.68      0.73        28
          7       0.63      0.88      0.73        95
          8       0.00      0.00      0.00         2
          9       1.00      0.75      0.86         4

avg / total       0.62      0.63      0.61       333


confusion_matrix
 [[29  3  0 17  1  3  4  0  0]
 [ 2 17  0  0  2  0 24  0  0]
 [ 0  0  5  1  1  0  2  0  0]
 [16  0  0 46  1  0  6  0  0]
 [ 5  0  0  3  6  2  8  0  0]
 [ 2  2  0  1  0 19  4  0  0]
 [ 3  6  1  1  0  0 84  0  0]
 [ 0  1  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  1  0  3]]


/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [32]:
parameters = {
              'n_estimators': [10, 50, 100, 200, 250, 500],
              'criterion':['gini','entropy'], 
              'max_depth':[None, 4, 6, 8, 10], 
              'min_samples_split':[2,4,6,8],
              'min_samples_leaf':[1, 3, 5, 8, 10], 
              'min_weight_fraction_leaf':[0, 0.1, 0.01, 0.5, 0.001], 
              'max_features':['log2','auto'], 
              'max_leaf_nodes':[None, 4, 8, 16, 32],
              'min_impurity_decrease':[0, 1e-3, 1e-4, 1e-5], 
              'class_weight':['balanced',None],
#               'bootstrap':[True, False],
#               'oob_score':[True, False]
#               'presort':[True, False] 
}
rf_rs = RandomizedSearchCV(rf_model, parameters, n_iter=100, n_jobs=-1)


In [33]:
evaluate_model(rf_rs)

log_loss
 1.40210320613
f1_score
 0.615124328168
accuracy_score
 0.675675675676

classification_report
              precision    recall  f1-score   support

          1       0.68      0.63      0.65        57
          2       0.67      0.67      0.67        45
          3       0.33      0.67      0.44         9
          4       0.75      0.62      0.68        69
          5       0.58      0.62      0.60        24
          6       1.00      0.64      0.78        28
          7       0.65      0.77      0.71        95
          8       0.00      0.00      0.00         2
          9       1.00      1.00      1.00         4

avg / total       0.70      0.68      0.68       333


confusion_matrix
 [[36  3  0  8  4  0  6  0  0]
 [ 1 30  0  1  1  0 12  0  0]
 [ 0  0  6  1  1  0  1  0  0]
 [11  0  3 43  2  0 10  0  0]
 [ 2  0  1  2 15  0  4  0  0]
 [ 2  2  0  0  2 18  4  0  0]
 [ 1 10  8  2  1  0 73  0  0]
 [ 0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  4]]


/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [34]:
pd.DataFrame(rf_rs.cv_results_).transpose()

/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
 

0   \
mean_fit_time                                                             0.39338   
mean_score_time                                                          0.749967   
mean_test_score                                                          0.290495   
mean_train_score                                                         0.338801   
param_class_weight                                                       balanced   
param_criterion                                                              gini   
param_max_depth                                                                 4   
param_max_features                                                           log2   
param_max_leaf_nodes                                                           16   
param_min_impurity_decrease                                                0.0001   
param_min_samples_leaf                                                          8   
param_min_samples_split                                                         6   
param_min_weight_fraction_leaf                                              0.001   
param_n_estimators                                                             50   
params                          {'n_estimators': 50, 'min_weight_fraction_leaf...   
rank_test_score                                                                59   
split0_test_score                                                         0.29029   
split0_train_score                                                       0.308195   
split1_test_score                                                        0.265797   
split1_train_score                                                       0.316424   
split2_test_score                                                        0.315524   
split2_train_score                                                       0.391784   
std_fit_time                                                            0.0132295   
std_score_time                                                          0.0626491   
std_test_score                                                           0.020286   
std_train_score                                                         0.0376148   

                                                                               1   \
mean_fit_time                                                            0.719029   
mean_score_time                                                           1.46357   
mean_test_score                                                          0.426372   
mean_train_score                                                         0.492814   
param_class_weight                                                       balanced   
param_criterion                                                              gini   
param_max_depth                                                                10   
param_max_features                                                           auto   
param_max_leaf_nodes                                                           32   
param_min_impurity_decrease                                                 1e-05   
param_min_samples_leaf                                                          5   
param_min_samples_split                                                         2   
param_min_weight_fraction_leaf                                                0.1   
param_n_estimators                                                             50   
params                          {'n_estimators': 50, 'min_weight_fraction_leaf...   
rank_test_score                                                                33   
split0_test_score                                                        0.417417   
split0_train_score                                                       0.497738   
split1_test_score                                                        0.424273   
split1_train_score                                                        0.49774  

## Extreme Randomization Trees

In [35]:
from sklearn.ensemble import ExtraTreesClassifier
xtr_model = ExtraTreesClassifier()

In [36]:
evaluate_model(xtr_model)

log_loss
 3.86575438533
f1_score
 0.505023576656
accuracy_score
 0.630630630631

classification_report
              precision    recall  f1-score   support

          1       0.62      0.63      0.63        57
          2       0.70      0.47      0.56        45
          3       0.14      0.11      0.12         9
          4       0.68      0.65      0.67        69
          5       0.47      0.29      0.36        24
          6       0.79      0.54      0.64        28
          7       0.61      0.86      0.71        95
          8       0.00      0.00      0.00         2
          9       1.00      0.75      0.86         4

avg / total       0.63      0.63      0.62       333


confusion_matrix
 [[36  1  0 13  1  1  5  0  0]
 [ 1 21  0  0  1  0 22  0  0]
 [ 0  0  1  1  1  1  5  0  0]
 [10  1  1 45  2  1  9  0  0]
 [ 5  0  1  4  7  1  6  0  0]
 [ 2  4  0  1  2 15  4  0  0]
 [ 4  2  4  2  1  0 82  0  0]
 [ 0  1  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  0  1  0  3]]


/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [37]:
parameters = {
              'n_estimators': [10, 50, 100, 200, 250, 500],
              'criterion':['gini','entropy'], 
              'max_depth':[None, 4, 6, 8, 10], 
              'min_samples_split':[2,4,6,8],
              'min_samples_leaf':[1, 3, 5, 8, 10], 
              'min_weight_fraction_leaf':[0, 0.1, 0.01, 0.5, 0.001], 
              'max_features':['log2','auto'], 
              'max_leaf_nodes':[None, 4, 8, 16, 32],
              'min_impurity_decrease':[0, 1e-3, 1e-4, 1e-5], 
              'class_weight':['balanced',None],
#               'bootstrap':[True, False],
#               'oob_score':[True, False]
#               'presort':[True, False] 
}
xtr_rs = RandomizedSearchCV(xtr_model, parameters, n_iter=100, n_jobs=-1)


In [38]:
evaluate_model(xtr_rs)

log_loss
 1.28911404362
f1_score
 0.583032846735
accuracy_score
 0.648648648649

classification_report
              precision    recall  f1-score   support

          1       0.70      0.56      0.62        57
          2       0.64      0.62      0.63        45
          3       0.33      0.67      0.44         9
          4       0.75      0.55      0.63        69
          5       0.55      0.67      0.60        24
          6       0.86      0.64      0.73        28
          7       0.62      0.78      0.69        95
          8       0.00      0.00      0.00         2
          9       0.80      1.00      0.89         4

avg / total       0.67      0.65      0.65       333


confusion_matrix
 [[32  5  0  7  4  1  8  0  0]
 [ 0 28  0  0  1  0 16  0  0]
 [ 0  0  6  1  1  0  1  0  0]
 [13  0  3 38  2  1 12  0  0]
 [ 0  0  1  3 16  0  4  0  0]
 [ 1  1  0  1  3 18  4  0  0]
 [ 0 10  8  1  2  0 74  0  0]
 [ 0  0  0  0  0  1  0  0  1]
 [ 0  0  0  0  0  0  0  0  4]]


/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [39]:
pd.DataFrame(xtr_rs.cv_results_).transpose()

/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('mean_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
/home/bicepjai/Programs/anaconda3/envs/dsotc-c3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:122: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
 

0   \
mean_fit_time                                                             1.63213   
mean_score_time                                                           15.7786   
mean_test_score                                                          0.171352   
mean_train_score                                                         0.171214   
param_class_weight                                                       balanced   
param_criterion                                                              gini   
param_max_depth                                                                 4   
param_max_features                                                           auto   
param_max_leaf_nodes                                                           16   
param_min_impurity_decrease                                                 1e-05   
param_min_samples_leaf                                                          1   
param_min_samples_split                                                         4   
param_min_weight_fraction_leaf                                                0.5   
param_n_estimators                                                            500   
params                          {'n_estimators': 500, 'min_weight_fraction_lea...   
rank_test_score                                                                83   
split0_test_score                                                        0.171171   
split0_train_score                                                        0.17094   
split1_test_score                                                         0.20662   
split1_train_score                                                       0.206429   
split2_test_score                                                        0.136089   
split2_train_score                                                       0.136273   
std_fit_time                                                             0.217234   
std_score_time                                                            1.02605   
std_test_score                                                          0.0287727   
std_train_score                                                         0.0286419   

                                                                               1   \
mean_fit_time                                                               0.984   
mean_score_time                                                           1.49318   
mean_test_score                                                          0.400268   
mean_train_score                                                         0.415994   
param_class_weight                                                           None   
param_criterion                                                              gini   
param_max_depth                                                              None   
param_max_features                                                           auto   
param_max_leaf_nodes                                                           16   
param_min_impurity_decrease                                                 1e-05   
param_min_samples_leaf                                                          5   
param_min_samples_split                                                         2   
param_min_weight_fraction_leaf                                               0.01   
param_n_estimators                                                             50   
params                          {'n_estimators': 50, 'min_weight_fraction_leaf...   
rank_test_score                                                                16   
split0_test_score                                                        0.396396   
split0_train_score                                                       0.409251   
split1_test_score                                                        0.416249   
split1_train_score                                                       0.421396  

## Saving models run

### stage1

In [ ]:
pickle.dump(nb_model, open('stage1/nb_model', 'wb'))
pickle.dump(svc_model, open('stage1/svc_model', 'wb'))
pickle.dump(smreg_model, open('stage1/smreg_model', 'wb'))
pickle.dump(knn_model, open('stage1/knn_model', 'wb'))
pickle.dump(pag_model, open('stage1/pag_model', 'wb'))
pickle.dump(qda_model, open('stage1/qda_model', 'wb'))
pickle.dump(dt_model, open('stage1/qda_model', 'wb'))
pickle.dump(adab_model, open('stage1/adab_model', 'wb'))
pickle.dump(rf_model, open('stage1/rf_model', 'wb'))
pickle.dump(xtr_model, open('stage1/xtr_model', 'wb'))

In [ ]:
from sklearn.ensemble import VotingClassifier

## Load classifiers

In [ ]:
nb_model    = pickle.load(open('stage1/nb_model', 'rb'))
svc_model   = pickle.load(open('stage1/svc_model', 'rb'))
smreg_model = pickle.load(open('stage1/smreg_model', 'rb'))
knn_model   = pickle.load(open('stage1/knn_model', 'rb'))
pag_model   = pickle.load(open('stage1/pag_model', 'rb'))
qda_model   = pickle.load(open('stage1/qda_model', 'rb'))
dt_model    = pickle.load(open('stage1/qda_model', 'rb'))
adab_model  = pickle.load(open('stage1/adab_model', 'rb'))
rf_model    = pickle.load(open('stage1/rf_model', 'rb'))
xtr_model   = pickle.load(open('stage1/xtr_model', 'rb'))

## Average on probabilities

In [ ]:
estimators_returning_probabilities = [
                    ("NB", nb_model),           
                    ("SVM", svc_model),         
                    ("Softmax", smreg_model),  
                    ("KNN", knn_model),         
#                     ("PasAgg", pag_model),      
#                     ("QDA", qda_model),         
                    ("DecisionTree", dt_model), 
                    ("ADABoost", adab_model),   
                    ("RandomForest", rf_model),
                    ("ExtremeRand", xtr_model)
                 ]

In [ ]:
def average_predicted_probabilities(local_data):
    nof_data = local_data.shape[0]
    mean_probs = np.zeros((nof_data, 9))
    for name, estimator in estimators_returning_probabilities:
        mean_probs += estimator.predict_proba(local_data)
    return mean_probs/nof_data

In [ ]:
y_pred = average_predicted_probabilities(x_test_tf)
print("log_loss\n", log_loss(y_test, y_pred, labels=range(1,10)))